require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    # - 'spec/**/*'
    - 'lib/tasks/ci.rake'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/support/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*'
Rails:
  Enabled: true
Style/EmptyMethod:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Style/CollectionMethods:
  Enabled: false
Style/Lambda:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 40
Metrics/ClassLength:
  Enabled: true
  Max: 250
Style/WordArray:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassVars:
  Exclude:
    - 'app/graphql/mutations/base_mutation.rb'
Metrics/BlockLength:
  Exclude:
    - 'app/models/concerns/*.rb'
Naming/PredicateName:
  Exclude:
    - 'app/graphql/connections/*.rb'
    - 'app/graphql/mutations/base_field.rb'
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
